version: '3'
services:
  app:
    image: proyecto-models
    restart: always
    networks:
      - postgres-net
      - redis-net
    external_links:
      - redis:redis
      - postgres:postgres
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

networks:
  postgres-net:
    external: true
  redis-net:
    external: true